[site]
name = "Blaze"
style = "book"

[menu]
names = ["Home", "About", "Subjects", "Blog", "Contact"]
links = ["/", "/about", "/subjects", "/blog", "/contact"]

[media]
include = [
    
]

[analytics]
tag = "analytics-tag.html"